server:
  port: 9091

financialModUrl: https://financialmodelingprep.com/api/v3
alphavantageUrl: https://www.alphavantage.co
alphavantageToken: 9D9L9BQSP00TNWIF

logging:
  level:
    root: error
    org:
      springframework: info
    app: info

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  profiles:
    active: @active.profile@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 20 #batch size here affect every entitymanager
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
          new_generator_mappings: true
          reWriteBatchedInserts: true
---
spring:
  profiles: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/stockDev
    username: stockDev
    password: stockDev
logging:
  level:
    app: debug
    org:
      springframework:
        transaction:
          interceptor: trace
      hibernate:
        engine:
          jdbc:
            batch:
              internal:
                BatchingBatch: debug #to log if batching is working